// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWHI8HcZJRFs4wXeM5g4OSImHodbrWFM',
    appId: '1:831309978479:web:07def68c325e4186b2269a',
    messagingSenderId: '831309978479',
    projectId: 'amigazos-db',
    authDomain: 'amigazos-db.firebaseapp.com',
    storageBucket: 'amigazos-db.firebasestorage.app',
    measurementId: 'G-L0J0S1CH9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-ZHEnevtJ9YEpwPfqRJrnTz74ka2P94',
    appId: '1:831309978479:android:2801c58bee626122b2269a',
    messagingSenderId: '831309978479',
    projectId: 'amigazos-db',
    storageBucket: 'amigazos-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZkPKBXxwaMCV0Da7cPeXBVdT9qiOTow',
    appId: '1:831309978479:ios:8e99a949fa99f16bb2269a',
    messagingSenderId: '831309978479',
    projectId: 'amigazos-db',
    storageBucket: 'amigazos-db.firebasestorage.app',
    androidClientId: '831309978479-kmk6uqokqvkkp6qvoaabdvvvpuds0i4t.apps.googleusercontent.com',
    iosClientId: '831309978479-jeclpma2vel4vv53h295opuqm3ras23h.apps.googleusercontent.com',
    iosBundleId: 'com.mhc.amigazos.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZkPKBXxwaMCV0Da7cPeXBVdT9qiOTow',
    appId: '1:831309978479:ios:35d277ac4ec9155ab2269a',
    messagingSenderId: '831309978479',
    projectId: 'amigazos-db',
    storageBucket: 'amigazos-db.firebasestorage.app',
    iosClientId:
        '831309978479-66531r40scuuq2sfm6082m5dd69uvkg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.amigazos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiWHI8HcZJRFs4wXeM5g4OSImHodbrWFM',
    appId: '1:831309978479:web:701890befc1ee5c2b2269a',
    messagingSenderId: '831309978479',
    projectId: 'amigazos-db',
    authDomain: 'amigazos-db.firebaseapp.com',
    storageBucket: 'amigazos-db.firebasestorage.app',
    measurementId: 'G-V5ESNDYZYQ',
  );

}