// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACDQrZZvAaSoWEwIAdHcu26oNnwFsuCD8',
    appId: '1:1045900816388:web:fae12412a88c1b54e84551',
    messagingSenderId: '1045900816388',
    projectId: 'guayabita-db',
    authDomain: 'guayabita-db.firebaseapp.com',
    storageBucket: 'guayabita-db.firebasestorage.app',
    measurementId: 'G-75JJV05HFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7q7G1hyZwneiaB_p9sx4YAh5tzt58VdQ',
    appId: '1:1045900816388:android:24a6e519f3b4d2a8e84551',
    messagingSenderId: '1045900816388',
    projectId: 'guayabita-db',
    storageBucket: 'guayabita-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD_B-T1hpma654-PSvPoZuQy7juQJSrmQ',
    appId: '1:1045900816388:ios:c97ae1c75726b3a5e84551',
    messagingSenderId: '1045900816388',
    projectId: 'guayabita-db',
    storageBucket: 'guayabita-db.firebasestorage.app',
    iosBundleId: 'com.example.guayabita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD_B-T1hpma654-PSvPoZuQy7juQJSrmQ',
    appId: '1:1045900816388:ios:c97ae1c75726b3a5e84551',
    messagingSenderId: '1045900816388',
    projectId: 'guayabita-db',
    storageBucket: 'guayabita-db.firebasestorage.app',
    iosBundleId: 'com.example.guayabita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACDQrZZvAaSoWEwIAdHcu26oNnwFsuCD8',
    appId: '1:1045900816388:web:6a0ee7a6078aa902e84551',
    messagingSenderId: '1045900816388',
    projectId: 'guayabita-db',
    authDomain: 'guayabita-db.firebaseapp.com',
    storageBucket: 'guayabita-db.firebasestorage.app',
    measurementId: 'G-43KRVWYZG1',
  );
}
